WIP: Replace and combine timetables
HSLdevcom/jore4-timetables-api pull request #3
Opened 2023-09-08 09:58 UTC by Leitsi

Also related to this: https://github.com/HSLdevcom/jore4-hasura/pull/187

2023-09-08 11:50 UTC, jarkkoka requested changes
> Reviewed 12 of 92 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 12 of 92 files reviewed, 20 unresolved discussions (waiting on @Leitsi)

___
*[`.gitmodules` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoI_O78O4JDGyDa0GJ:-NdoI_O78O4JDGyDa0GK:b-s1qgj3) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/.gitmodules#L2)):*
> ```gitconfig
> [submodule "jore4-hasura"]
> 	path = jore4-hasura
> ```

tab to space
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 29 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoJ110B61-wviCALLX:-NdoJ110B61-wviCALLY:bawgi05) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L29)):*
> ```Kotlin
> 
>     data class CombineTimetablesResponseBody(
>         val combinedIntoVehicleScheduleFrameIds: List<UUID>,
> ```

Trailing comma. Maybe should setup ktlint to strip there as is done in `jore4-hastus` repository.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoJGagAbMATE471ucC:-NdoJGagAbMATE471ucD:bb48xj0) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L34)):*
> ```Kotlin
>     @PostMapping("combine")
>     fun combine(@RequestBody requestBody: CombineOrReplaceTimetablesRequestBody): ResponseEntity<CombineTimetablesResponseBody> {
>         LOGGER.info("Combine api, request: ${requestBody.stagingVehicleScheduleFrameIds}, ${requestBody.targetPriority}")
> ```

It's better to use `LOGGER.info { "..." }` syntax when strings are referencing variable values.

The string construction is done lazily in the block only if the log level is set to `INFO` level (or below like `DEBUG` or `TRACE`).
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 47 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoJD7PDT3EP_Fc944Z:-NdoJD7QBYkYjWqL4OhS:bs8fk66) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L47)):*
> ```Kotlin
> 
>     data class ReplaceTimetablesResponseBody(
>         val replacedVehicleScheduleFrameIds: List<UUID>,
> ```

Trailing comma. IMO this looks very odd in Java/Kotlin code.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 52 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoJWad9EY6Lu3LKG6S:-NdoJWad9EY6Lu3LKG6T:b-dx2g67) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L52)):*
> ```Kotlin
>     @PostMapping("replace")
>     fun replace(@RequestBody requestBody: CombineOrReplaceTimetablesRequestBody): ResponseEntity<ReplaceTimetablesResponseBody> {
>         LOGGER.info("Replace api, request: ${requestBody.stagingVehicleScheduleFrameIds}, ${requestBody.targetPriority}")
> ```

It's better to use `LOGGER.info { "..." }` syntax when strings are referencing variable values. 
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/config/WebSecurityConfig.kt` line 32 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoJdKICOJcmYOnVucQ:-NdoJdKICOJcmYOnVucR:bcfwp6b) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/config/WebSecurityConfig.kt#L32)):*
> ```Kotlin
>                     )
>                     .permitAll()
>                 it
> ```

Strip `it` for consistent style in chaining function calls.

E.g. `.anyRequest().denyAll()` below is not prefixed with `it.`
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoK1NNCKo4UbhgFWf7:-NdoK1NNCKo4UbhgFWf8:b-g4gn7g) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L14)):*
> ```Kotlin
> import org.springframework.stereotype.Service
> import org.springframework.transaction.annotation.Transactional
> import java.util.*
> ```

No star imports. You should setup IDEA to not do this automatically.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 35 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoKD_yDVMvhkdp4T8U:-NdoKD_yDVMvhkdp4T8V:bpoy0zt) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L35)):*
> ```Kotlin
>         validateTargetPriority(targetPriority)
> 
>         LOGGER.info("Combining timetables... $stagingVehicleScheduleFrameId to priority $targetPriority")
> ```

`LOGGER.info { ... }`
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoKHbH4L2Cw3cKAUE_:-NdoKHbH4L2Cw3cKAUEa:b6dgpe4) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L40)):*
> ```Kotlin
> 
>         val targetVehicleScheduleFrames = fetchTargetVehicleScheduleFrames(stagingVehicleScheduleFrame, targetPriority)
>         LOGGER.info("Found ${targetVehicleScheduleFrames.size} target vehicle schedule frames.")
> ```

Preferred: `LOGGER.info { ... }`
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 45 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoKhnx7W5oms0bmBSZ:-NdoKhnx7W5oms0bmBS_:bk7z5vd) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L45)):*
> ```Kotlin
>         if (targetVehicleScheduleFrames.size > 1) {
>             // TODO: this probably needs better handling.
>             throw Error("Multiple target timetables found.")
> ```

What is your reasoning to use `Error` instead of an `*Exception` class? Basically, I have never seen `Error`s thrown from own code. I think we should stick to exceptions.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoXhZt-8NmrNhVt1HU:-NdoXhZt-8NmrNhVt1HV:b-fkrz2k) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L21)):*
> ```Kotlin
> data class FramesReplacedByStaging(
>     val stagingVehicleScheduleFrameId: UUID,
>     val replacedVehicleScheduleFrameId: UUID,
> ```

Trailing comma is very odd in Java/Kotlin. 
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 38 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoXsoX6p94NNEuY3V0:-NdoXsoX6p94NNEuY3V1:b-a9s1lv) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L38)):*
> ```Kotlin
>         validateTargetPriority(targetPriority)
> 
>         LOGGER.info("Replacing timetables... $stagingVehicleScheduleFrameId to priority $targetPriority")
> ```

Preferred way: `LO [...]

2023-09-08 11:56 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 12 of 92 files reviewed, 21 unresolved discussions (waiting on @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdodR_e1tXuOSYJsj7L:-NdodR_e1tXuOSYJsj7M:b-89zqv5) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L11)):*
> ```Kotlin
> import org.jooq.*
> import org.springframework.stereotype.Service
> import org.springframework.transaction.annotation.Transactional
> ```

Star imports are against the coding convertions in this project.


<!-- Sent from Reviewable.io -->

2023-09-08 12:26 UTC, culka reviewed
> Reviewed 75 of 92 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 87 of 92 files reviewed, 22 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 27 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ndohel_3TZHA2mxx6ex:-Ndohel_3TZHA2mxx6ey:b-nd7ns9) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L27)):*
> ```Kotlin
> class ReplaceTimetablesService(private val dsl: DSLContext) {
>     @Transactional(readOnly = false)
>     fun replaceTimetables(stagingVehicleScheduleFrameIds: List<UUID>, targetPriority: TimetablesPriority): List<UUID> {
> ```

Unless you are doing some logging or other operations with the results, functions like this can be written without curly braces and return, like



_Code snippet:_
```Kotlin
    fun replaceTimetables(stagingVehicleScheduleFrameIds: List<UUID>, targetPriority: TimetablesPriority): List<UUID> =
        stagingVehicleScheduleFrameIds.map { stagingFrameId ->
            processSingleStagingFrameReplacements(stagingFrameId, targetPriority)
        }.flatten()
```


<!-- Sent from Reviewable.io -->

2023-09-11 06:00 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 87 of 92 files reviewed, 22 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 29 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoJ110B61-wviCALLX:-NdouMQ4CiLdukrRXlz1:bghct40) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L29)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Trailing comma. Maybe should setup ktlint to strip there as is done in `jore4-hastus` repository.
</blockquote></details>

Ktlint had not been ran, it autofixes all of these. :heavy_check_mark: 
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoJGagAbMATE471ucC:-Ndp-wPUDbyNJ2m3qecC:b73gh0l) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L34)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It's better to use `LOGGER.info { "..." }` syntax when strings are referencing variable values.

The string construction is done lazily in the block only if the log level is set to `INFO` level (or below like `DEBUG` or `TRACE`).
</blockquote></details>

:ok_hand:  Good rationale. Think I fixed all of these. Tried to research if there would be a lint / editorconfig to catch these, but couldn't find.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoK1NNCKo4UbhgFWf7:-NdowYTrDknmAQ5_KUWY:b5nis7x) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L14)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

No star imports. You should setup IDEA to not do this automatically.
</blockquote></details>

Removed other instances of this (again, missed because Ktlint had not been ran), but left the java util star imports: https://pinterest.github.io/ktlint/0.49.1/faq/#why-is-wildcard-import-javautil-not-reported-by-the-no-wildcard-imports-rule
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 45 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoKhnx7W5oms0bmBSZ:-NdowgHt9U_oKx0oKaDF:bd4qg7c) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L45)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

What is your reasoning to use `Error` instead of an `*Exception` class? Basically, I have never seen `Error`s thrown from own code. I think we should stick to exceptions.
</blockquote></details>

Ignorance basically, will change. Will add custom error classes for each case I think.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 28 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ndo_LNc9HDj7S5jpW_W:-Ne1nOPHCkERxDapxHsX:b-5g2ldp) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L28)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO, non-null value should always be returned from this helper method.

If a null value is got from the DB, it's better to throw an exception (e.g. custom `NotFoundException` residing in e.g. `util` package and taking a `String` message) and log here for what ID a frame was not found.
</blockquote></details>

:thumbsup: changed. Don't think this kind of test helper merits a custom class so just throws a basic `Exception` now.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 57 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NdoZxcu0bMlILWD3cRB:-Ndp9Ugy9an8kqltcaKH:b-bh1vd0) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L57)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`!!` is most often code smell. Try to avoid them. You are basically throwing an unexplained `NullPointerException` here.
</blockquote></details>

:thumbsup: added an exception to the helper method instead.


<!-- Sent from Reviewable.io -->

2023-09-12 13:26 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 87 of 92 files reviewed, 21 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 19 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8ZD2gEiX-gApoyfsv:-Ne8ZD2gEiX-gApoyfsw:b-9a9mq1) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L19)):*
> ```Kotlin
> 
> @Service
> class CombineTimetablesService(private val dsl: DSLContext) {
> ```

I wrote a comment about Repository layer and classes in another file. IMO we should follow that pattern mentioned in that comment (like is done in other Jore4 backend repositories).
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 97 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne3UKVV6E-UGadMV53b:-Ne3UKVV6E-UGadMV53c:bxewqce) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L97)):*
> ```Kotlin
>                 overlappingSchedulesCTE
>                     .fields(
>                         DSL.name("stagingVehicleScheduleFrameId"),
> ```

These two `DSL.name("...")` are repeated twice (appear above also). I'd assign these to variables to reduce code redundancy.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 79 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8WiNSCOVnL37_Q48x:-Ne8WiNSCOVnL37_Q48y:b-l31gg0) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L79)):*
> ```Kotlin
>     }
> 
>     private fun fetchVehicleScheduleFramesToReplace(
> ```

In `jore4-map-matching` and `jore4-jore3-importer` repository, we follow the general pattern in Spring projects that the methods executing SQL queries are introduced in separate "Repository" classes. This allows SQL queries to be tested in isolation and is the preferred way in Jore4 as well.

This same principle applies to the two lattermost methods in this class as well. I'd suggest moving them to a `XyzYouNameItRepository` (maybe more than one if suitable).

The common architectural structure of Spring (Boot) projects is that the controller (web) layer is thin and calls the (business) Service layer.
The Service layer then calls the methods in the Repository (sometimes called DAO) layer below.
The Repository layer is is directly connected to the database.

In jOOQ projects, the `DSLContext` object is injected into Repository classes.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 82 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8WZGbDpbOVpWIOo2T:-Ne8WZGbDpbOVpWIOo2U:b-q6fil8) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L82)):*
> ```Kotlin
>         stagingVehicleScheduleFrameId: UUID,
>         targetPriority: TimetablesPriority
>     ): MutableList<FramesReplacedByStaging> {
> ```

Returning immutable `List` is preferred over returning `MutableList`.


<!-- Sent from Reviewable.io -->

2023-09-12 14:16 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 79 of 94 files reviewed, 23 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 23 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8jY8wAQWNAkk9Btay:-Ne8jY8wAQWNAkk9Btaz:b-bns80x) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L23)):*
> ```Kotlin
>     private val replaceTimetablesService: ReplaceTimetablesService
> ) {
>     data class CombineOrReplaceTimetablesRequestBody(
> ```

I suggest adding validation for `targetPriority` by adding the following method into the body of data class:

```kotlin
@AssertTrue(message = "false")  
fun isTargetPriorityValid(): Boolean = TimetablesPriority.fromInt(targetPriority) in listOf(  
    TimetablesPriority.STANDARD,  
    TimetablesPriority.TEMPORARY,  
    TimetablesPriority.SPECIAL)
```
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 33 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8ibLM1-FakjUDn5-1:-Ne8ibLM1-FakjUDn5-2:b-vytsi5) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L33)):*
> ```Kotlin
> 
>     @PostMapping("combine")
>     fun combine(@RequestBody requestBody: CombineOrReplaceTimetablesRequestBody): ResponseEntity<CombineTimetablesResponseBody> {
> ```

Consider adding `@Valid` annotation to enable validation if adding above `isTargetPriorityValid()` method.


<!-- Sent from Reviewable.io -->

2023-09-12 14:18 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 79 of 94 files reviewed, 23 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 51 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8kN2g3_HetCnUAXg-:-Ne8kN2g3_HetCnUAXg0:b-vytsi5) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L51)):*
> ```Kotlin
> 
>     @PostMapping("replace")
>     fun replace(@RequestBody requestBody: CombineOrReplaceTimetablesRequestBody): ResponseEntity<ReplaceTimetablesResponseBody> {
> ```

Consider adding `@Valid` annotation to enable validation if adding above `isTargetPriorityValid()` method.


<!-- Sent from Reviewable.io -->

2023-09-12 14:37 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 79 of 94 files reviewed, 23 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 23 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8jY8wAQWNAkk9Btay:-Ne8oHVq7VBgEOa9c8YF:b-lpt3g5) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I suggest adding validation for `targetPriority` by adding the following method into the body of data class:

```kotlin
@AssertTrue(message = "false")  
fun isTargetPriorityValid(): Boolean = TimetablesPriority.fromInt(targetPriority) in listOf(  
    TimetablesPriority.STANDARD,  
    TimetablesPriority.TEMPORARY,  
    TimetablesPriority.SPECIAL)
```
</blockquote></details>

Follow-up. I see you already perform `targetPriority` validation in the service level.

However, I see that there should be an API contract that `targetPriority` integer value must be (at least) some real value known in Jore.

Hence, I modify the code suggestion to be more like:

```kotlin
fun isTargetPriorityValid(): Boolean = TimetablesPriority.fromInt(targetPriority) != null
```


<!-- Sent from Reviewable.io -->

2023-09-12 14:41 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 79 of 94 files reviewed, 25 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 20 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8pS-S22xgAl505YqW:-Ne8pS-S22xgAl505YqX:b-2el5mc) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L20)):*
> ```Kotlin
> @Service
> class CombineTimetablesService(private val dsl: DSLContext) {
>     @Transactional(readOnly = false)
> ```

Since the default value of `readOnly` is `false`, I would omit the attribute. It is easier to read the code and note the read-only behavior being toggled on when explicitly mentioned.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8poqi7urHqkP_ksTy:-Ne8poqjAMC0RyIIAovv:b-2el5mc) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L31)):*
> ```Kotlin
>     }
> 
>     @Transactional(readOnly = false)
> ```

Since the default value of `readOnly` is `false`, I would omit the attribute. It is easier to read the code and note the read-only behavior being toggled on when explicitly mentioned.


<!-- Sent from Reviewable.io -->

2023-09-12 14:47 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 79 of 94 files reviewed, 26 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 45 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8qwT0A2n4-RCfhcvN:-Ne8qwT0A2n4-RCfhcvO:b-xiy0o5) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L45)):*
> ```Kotlin
>         if (targetVehicleScheduleFrames.size > 1) {
>             // TODO: this probably needs better handling.
>             throw Exception("Multiple target timetables found.")
> ```

You should not throw checked exceptions (not inheriting from `RuntimeException`) if not explicitly adding `rollbackFor = [Exception::class]` attribute to the `@Transactional` annotation.

In its default configuration, the Spring Framework’s transaction infrastructure code marks a transaction for rollback only in the case of runtime, unchecked exceptions.


<!-- Sent from Reviewable.io -->

2023-09-14 08:47 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 79 of 94 files reviewed, 26 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 23 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8jY8wAQWNAkk9Btay:-NeHrYN4En7b-FyR-NmB:b-rsnuwg) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Follow-up. I see you already perform `targetPriority` validation in the service level.

However, I see that there should be an API contract that `targetPriority` integer value must be (at least) some real value known in Jore.

Hence, I modify the code suggestion to be more like:

```kotlin
fun isTargetPriorityValid(): Boolean = TimetablesPriority.fromInt(targetPriority) != null
```
</blockquote></details>

:thumbsup:  done. Used try catch though, for easier handling inside the controller method.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 20 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8pS-S22xgAl505YqW:-NeHQSFh4c-SGzABoMEU:b-vak2nj) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7751c75558ca6a6585ef57a867d0b3b7378cac2e/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L20)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Now, as a seasoned Spring coder, my first reaction was that the transaction should not be marked read-only when it actually wasn't
</blockquote></details>

:thumbsup:  omitted.


<!-- Sent from Reviewable.io -->

2023-09-15 07:14 UTC, jarkkoka requested changes
> Reviewed 3 of 14 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 14 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`README.md` line 65 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMIMlp-D2uuJlRYu1C:-NeMIMlqCDTvwjcqGzUR:bqbn2w1) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/README.md#L65)):*
> ```Markdown
> - Additionally, minimize the use of mutable variables, using `val` whenever possible.
> - In tests, write test function names with backticks instead of `@DisplayName` annotation, eg:
>   ``
> ```

I'm under the impression that there should be a triple backtick for code block instead of a double?? Like said in <https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks>
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 60 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMg1_26XdD84C6DJyB:-NeMg1_26XdD84C6DJyC:b-5roykc) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L60)):*
> ```Kotlin
>     }
> 
>     private fun validateTargetPriority(targetPriority: TimetablesPriority) {
> ```

This is of static nature, i.e. it does not depend on the state of the class instance. Hence, move this method to a companion object.


<!-- Sent from Reviewable.io -->

2023-09-15 07:17 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 15 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 62 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMgeZpEj2wSE2vCr0Z:-NeMgeZpEj2wSE2vCr0_:bqiot85) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L62)):*
> ```Kotlin
>     private fun validateTargetPriority(targetPriority: TimetablesPriority) {
>         if (targetPriority in listOf(TimetablesPriority.STAGING)) {
>             throw IllegalArgumentException("Can not set priority $targetPriority as target.")
> ```

I would introduce `InvalidTargetPriorityException` class from testing perspective.


<!-- Sent from Reviewable.io -->

2023-09-15 07:18 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 16 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 171 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMgyX2C2v9qYWIbeBe:-NeMgyX2C2v9qYWIbeBf:b-t6sx49) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L171)):*
> ```Kotlin
>         stagingFrame: VehicleScheduleFrameRecord
>     ): Int {
>         val newEnd = stagingFrame.validityStart!!.minusDays(1)
> ```

IMO `IllegalStateException` should be thrown (instead of `NullPointerException`) if `validityStart` is `null`.


<!-- Sent from Reviewable.io -->

2023-09-15 07:19 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 16 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 171 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMgyX2C2v9qYWIbeBe:-NeMhJng7o4m0IWuaqYZ:b-kt19zk) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L171)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `IllegalStateException` should be thrown (instead of `NullPointerException`) if `validityStart` is `null`.
</blockquote></details>

...possibly included with message "null validityStart encountered" or something similar


<!-- Sent from Reviewable.io -->

2023-09-15 07:24 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 17 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 57 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMiJ8824QwaXIFV-Bn:-NeMiJ8824QwaXIFV-Bo:b-d95143) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L57)):*
> ```Kotlin
>         promoteStagingFrameToPriority(stagingFrame, targetPriority)
> 
>         return replacements.map { it.vehicleScheduleFrameId!! }
> ```

Please add an explaining comment when using `!!` like below

```kotlin
return replacements.map {  
    // can never be null  
    it.vehicleScheduleFrameId!!  
}```
```



<!-- Sent from Reviewable.io -->

2023-09-15 07:25 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 17 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 62 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMgeZpEj2wSE2vCr0Z:-NeMiirs7JUhdxc5r_RC:b-fy03ks) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L62)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would introduce `InvalidTargetPriorityException` class from testing perspective.
</blockquote></details>

...or to enable better testability in other words.


<!-- Sent from Reviewable.io -->

2023-09-15 07:32 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 18 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 33 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMjE1U1snX2QBhkE0F:-NeMjE1U1snX2QBhkE0G:b-de61qb) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L33)):*
> ```Kotlin
> 
>     @Transactional
>     fun processSingleStagingFrameReplacements(
> ```

I recommend making this method non-public unless you plan to create JUnit tests for this particular method.

If you keep this method public, you should add the attribute `noRollbackFor=[RuntimeException::class]` to the `@Transactional` annotation, because if an exception is thrown from this method, the outer method (`replaceTimetables`) will likely fail because transaction is already "marked as rollback only", and the outer method cannot recover from it.


<!-- Sent from Reviewable.io -->

2023-09-15 07:38 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 18 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 33 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMjE1U1snX2QBhkE0F:-NeMkOX02FoAypCdMsyA:bx34rae) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I recommend making this method non-public unless you plan to create JUnit tests for this particular method.

If you keep this method public, you should add the attribute `noRollbackFor=[RuntimeException::class]` to the `@Transactional` annotation, because if an exception is thrown from this method, the outer method (`replaceTimetables`) will likely fail because transaction is already "marked as rollback only", and the outer method cannot recover from it.
</blockquote></details>

Oops, the last paragraph in the previous comment was probably wrong because the `@Transactional` annotation is ineffective (when called from the outer method) because it does not go through a (Spring-created) proxy but is called internally without Spring magic.

However, you should only make public those methods that are called from outside and are also tested.


<!-- Sent from Reviewable.io -->

2023-09-18 10:09 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 18 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`README.md` line 65 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMIMlp-D2uuJlRYu1C:-NeMmMDUA1A5a41bRtyJ:b-gnhync) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/README.md#L65)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'm under the impression that there should be a triple backtick for code block instead of a double?? Like said in <https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks>
</blockquote></details>

This is a special case since the code block contains a backtick as well.
But actually four backticks is the proper solution for that (even though 2 seems to work too), will change.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 79 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Ne8WiNSCOVnL37_Q48x:-NeRrwm77aTQ5DWfW55T:btd2tlj) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/736ad449928ee5059aa963d42c6366a8b350ef2f/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L79)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In `jore4-map-matching` and `jore4-jore3-importer` repository, we follow the general pattern in Spring projects that the methods executing SQL queries are introduced in separate "Repository" classes. This allows SQL queries to be tested in isolation and is the preferred way in Jore4 as well.

This same principle applies to the two lattermost methods in this class as well. I'd suggest moving them to a `XyzYouNameItRepository` (maybe more than one if suitable).

The common architectural structure of Spring (Boot) projects is that the controller (web) layer is thin and calls the (business) Service layer.
The Service layer then calls the methods in the Repository (sometimes called DAO) layer below.
The Repository layer is is directly connected to the database.

In jOOQ projects, the `DSLContext` object is injected into Repository classes.
</blockquote></details>

Moved. This also allowed us to remove lots of handwritten SQL, thanks to jOOQ DAOs.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 33 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMjE1U1snX2QBhkE0F:-NeRoJ_x5J41uENWugfU:b32z1l4) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Oops, the last paragraph in the previous comment was probably wrong because the `@Transactional` annotation is ineffective (when called from the outer method) because it does not go through a (Spring-created) proxy but is called internally without Spring magic.

However, you should only make public those methods that are called from outside and are also tested.
</blockquote></details>

This method is tested. In fact, most tests are targeted for this method instead of `replaceTimetables` because it is easier to test the logic for a single frame at a time. Tests to ensure this are still TODO.

`replaceTimetables` should work such that if any `processSingleStagingFrameReplacements` failes, then the whole transaction fails. Otherwise they could just as well be handled in separate HTTP requests.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 57 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMiJ8824QwaXIFV-Bn:-NeRp0Qp9lSOk-cUHXvi:blosy6e) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L57)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Please add an explaining comment when using `!!` like below

```kotlin
return replacements.map {  
    // can never be null  
    it.vehicleScheduleFrameId!!  
}```
```

</blockquote></details>

Makes sense, but I'm thinking do we actually want to do this? This would be required for every single place where we access properties on the jOOQ POJOs, since they are always marked as nullable, even in instances such as this when the row is fetched from DB and the columns can not be null. Feels like this is quite general knowledge that a developer working on this codebase would become familiar with quite quickly. Would it make more sense to eg. document this in README "good to know" details, instead of "polluting" codebase with lots of duplicate comments?

There is a very recent jOOQ addition that POJOs can be generated with non-nullable types (3.18 I think, we have newest = 3.18.6). See https://github.com/jOOQ/jOOQ/issues/10212
This is enabled by:
```
<generate>  
    <kotlinNotNullPojoAttributes>true</kotlinNotNullPojoAttributes>  
    <kotlinNotNullRecordAttributes>true</kotlinNotNullRecordAttributes>  
    <kotlinNotNullInterfaceAttributes>true</kotlinNotNullInterfaceAttributes>  
</generate>
```
Doesn't seem to solve all cases though, eg this id accessing. For VehicleScheduleFrame following class will be generated with these flags, note that id is still nullable:
```
data class VehicleScheduleFrame(  
    var vehicleScheduleFrameId: UUID? = null,  
    var nameI18n: JSONB? = null,  
    var validityStart: LocalDate,  
    var validityEnd: LocalDate,  
    var priority: Int,  
    var label: String,  
    var bookingLabel: String? = null,  
    var bookingDescriptionI18n: JSONB? = null,  
    var createdAt: OffsetDateTime? = null  
): Serializable {
```
Decided to enable these settings, don't see any reason not to. Removes some (but not all) need for `!!`, and should solve more problems than it causes.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 171 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMgyX2C2v9qYWIbeBe:-NeRs9ol64qB0ZBP500v:b-c8kpbc) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L171)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

...possibly included with message "null validityStart encountered" or something similar
</blockquote></details>

Can never be null, this is merely because of how jOOQ POJOs are structure. Discussion in another comment.


<!-- Sent from Reviewable.io -->

2023-09-20 06:46 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 16 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 171 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMgyX2C2v9qYWIbeBe:-NelKOQyDfg-jTsQRdjE:bmlfkf5) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L171)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Can never be null, this is merely because of how jOOQ POJOs are structure. Discussion in another comment.
</blockquote></details>

Alright. In that case, I'd like a comment here that says it can't be `null` (so as not to confuse anymore).


<!-- Sent from Reviewable.io -->

2023-09-20 06:48 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 16 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 171 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMgyX2C2v9qYWIbeBe:-NelKnjIA_06m3n9MGVi:bbclref) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L171)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Alright. In that case, I'd like a comment here that says it can't be `null` (so as not to confuse anymore).
</blockquote></details>

As I said before, these `!!`s are a type of code smell that should be avoided, but if avoiding them is not possible, then it would be desirable to provide an explanation.


<!-- Sent from Reviewable.io -->

2023-09-20 13:39 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 85 of 94 files reviewed, 16 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 171 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMgyX2C2v9qYWIbeBe:-NemoDOa8tSZbLwP1kyb:bqd9ou5) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L171)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

As I said before, these `!!`s are a type of code smell that should be avoided, but if avoiding them is not possible, then it would be desirable to provide an explanation.
</blockquote></details>

These `!!` got removed thanks to changes to how jOOQ POJOs are generated.


<!-- Sent from Reviewable.io -->

2023-09-21 12:50 UTC, jarkkoka requested changes
Good development happening!:
- Pretty clean code!
- Separate Exception classes introduced for different error cases is good
- Extensive set of JUnit tests, very nice

> Reviewed 2 of 14 files at r2, 7 of 71 files at r4, 1 of 1 files at r5, 5 of 5 files at r6, 2 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-:-NerjRVvD3MIQ06Irc5C:b-p3mrjp)* status: 71 of 143 files reviewed, 21 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`-- commits` line 21 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerULpT0xgb2XaxZco4):*
typo "exlucde"  -> "exclude"
___
*[`-- commits` line 26 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerUU3P888j-un69G7f):*
typo "columsn" -> "columns"
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 47 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerVCCK1grwiVrzK2Fd:-NerVCCK1grwiVrzK2Fe:b-m4drgz) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L47)):*
> ```Kotlin
>         requestBody: CombineOrReplaceTimetablesRequestBody
>     ): ResponseEntity<ReplaceTimetablesResponseBody> {
>         LOGGER.info { "Replace api, request: $requestBody" }
> ```

Quite verbose. Log level should use `debug` instead of `info`.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 73 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerVz5H7LQsXEQihU6U:-NerVz5H7LQsXEQihU6V:b16qz2p) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L73)):*
> ```Kotlin
>         LOGGER.error(ex.stackTraceToString())
> 
>         var httpStatus = HttpStatus.CONFLICT // Hasura only wants errors on 4xx range.
> ```

extensive `var` usage in this file. `var` should not be used unless there is mutation.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 19 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Nera7v3Dy-chCA9J5u6:-Nera7v3Dy-chCA9J5u7:b446ree) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L19)):*
> ```Kotlin
> @Repository
> class VehicleScheduleFrameRepository(private val dsl: DSLContext, config: DefaultConfiguration) : VehicleScheduleFrameDao(config) {
>     @Transactional
> ```

Since these repository methods are basically always called from another `@Transactional`-annotated method (in Service layer), you should add `noRollbackFor = [RuntimeException::class]` attribute to the `@Transactional` annotation and let the "outer" method handle the rollback (when it exits from the transactional scope). If you don't, in the event of a database constraint violation, this "inner" method marks the current transaction as "rollback-only", and the outer method cannot recover from this state.

So, this matters when the query execution fails (e.g., in case of database constraint violation).

This same applies all write transaction methods in the Repository layer.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 28 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeriQ1X6snlhgdS86s8:-NeriQ1X6snlhgdS86s9:b5pm409) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L28)):*
> ```Kotlin
> 
>         val stagingVehicleScheduleFrameIdField = DSL.field(DSL.name("stagingVehicleScheduleFrameId"), UUID::class.java)
>         val replacedVehicleScheduleFrameIdField =
> ```

You could reduce code duplication and the possibility of mismatching hand-written strings with the below code:

```kotlin
val stagingFrameIdName: Name = DSL.name("stagingVehicleScheduleFrameId")  
val replacedFrameIdName: Name = DSL.name("replacedVehicleScheduleFrameId")  
  
val stagingVehicleScheduleFrameIdField = DSL.field(stagingFrameIdName, UUID::class.java)  
val replacedVehicleScheduleFrameIdField = DSL.field(replacedFrameIdName, UUID::class.java)
```
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 39 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerirDo5-bUZqMxpXCh:-NerirDo5-bUZqMxpXCi:b-sz4c6y) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L39)):*
> ```Kotlin
>                     .fields(
>                         DSL.name("stagingVehicleScheduleFrameId"),
>                         DSL.name("replacedVehicleScheduleFrameId")
> ```

When using the above suggestion this goes like:

```kotlin
.fields(  
    stagingFrameIdName,  
    replacedFrameIdName  
)```
```

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 33 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMjE1U1snX2QBhkE0F:-Nerdd5zBQdOrWHMfOzJ:b-qezkjt) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L33)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This method is tested. In fact, most tests are targeted for this method instead of `replaceTimetables` because it is easier to test the logic for a single frame at a time. Tests to ensure this are still TODO.

`replaceTimetables` should work such that if any `processSingleStagingFrameReplacements` failes, then the whole transaction fails. Otherwise they could just as well be handled in separate HTTP requests.
</blockquote></details>

Ok, fair enough.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 57 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMiJ8824QwaXIFV-Bn:-NerdupG6qJT8KeRF5oa:bh54qzo) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L57)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Makes sense, but I'm thinking do we actually want to do this? This would be required for every single place where we access properties on the jOOQ POJOs, since they are always marked as nullable, even in instances such as this when the row is fetched from DB and the columns can not be null. Feels like this is quite general knowledge that a developer working on this codebase would become familiar with quite quickly. Would it make more sense to eg. document this in README "good to know" details, instead of "polluting" codebase with lots of duplicate comments?

There is a very recent jOOQ addition that POJOs can be generated with non-nullable types (3.18 I think, we have newest = 3.18.6). See https://github.com/jOOQ/jOOQ/issues/10212
This is enabled by:
```
<generate>  
    <kotlinNotNullPojoAttributes>true</kotlinNotNullPojoAttributes>  
    <kotlinNotNullRecordAttributes>true</kotlinNotNullRecordAttributes>  
    <kotlinNotNullInterfaceAttributes>true</kotlinNotNullInterfaceAttributes>  
</generate>
```
Doesn't seem to solve all cases though, eg this id accessing. For VehicleScheduleFrame following class will be generated with these flags, note that id is still nullable:
```
data class VehicleScheduleFrame(  
    var vehicleScheduleFrameId: UUID? = null,  
    var nameI18n: JSONB? = null,  
    var validityStart: LocalDa [...]

2023-09-21 13:02 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 71 of 143 files reviewed, 21 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 59 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerbQFNCMmy0XC9myIi:-Nero4M10AKysoCfngpy:b-5j1lrg) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L59)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO there is no reason that this method exists in this class. This method is only called internally in this class. You can call the repository method directly.
</blockquote></details>

Rationale for this: we will be adding another endpoint for fetching the vehicle schedule frames about to be replaced, see https://github.com/HSLdevcom/jore4/issues/1446 . That API will use this method. Thus it's public here, and tested.


<!-- Sent from Reviewable.io -->

2023-09-21 13:07 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 71 of 143 files reviewed, 19 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 59 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerbQFNCMmy0XC9myIi:-NerqXq24x-wEE1c2duk:b-jzx7lg) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L59)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Rationale for this: we will be adding another endpoint for fetching the vehicle schedule frames about to be replaced, see https://github.com/HSLdevcom/jore4/issues/1446 . That API will use this method. Thus it's public here, and tested.
</blockquote></details>

Ok, good to know.


<!-- Sent from Reviewable.io -->

2023-09-22 10:24 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 71 of 143 files reviewed, 17 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 19 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-Nera7v3Dy-chCA9J5u6:-NevogZhAbvqVWBTHBpr:b6yrwgz) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L19)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Since these repository methods are basically always called from another `@Transactional`-annotated method (in Service layer), you should add `noRollbackFor = [RuntimeException::class]` attribute to the `@Transactional` annotation and let the "outer" method handle the rollback (when it exits from the transactional scope). If you don't, in the event of a database constraint violation, this "inner" method marks the current transaction as "rollback-only", and the outer method cannot recover from this state.

So, this matters when the query execution fails (e.g., in case of database constraint violation).

This same applies all write transaction methods in the Repository layer.
</blockquote></details>

Added to `processSingleStagingFrameReplacements` since what you said holds true for that method. For other methods in this service, they are used or planned to be used from controllers so they shouldn't have this I think.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 28 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeriQ1X6snlhgdS86s8:-Nevk3mN71xRw76ryvYr:b-msondl) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L28)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You could reduce code duplication and the possibility of mismatching hand-written strings with the below code:

```kotlin
val stagingFrameIdName: Name = DSL.name("stagingVehicleScheduleFrameId")  
val replacedFrameIdName: Name = DSL.name("replacedVehicleScheduleFrameId")  
  
val stagingVehicleScheduleFrameIdField = DSL.field(stagingFrameIdName, UUID::class.java)  
val replacedVehicleScheduleFrameIdField = DSL.field(replacedFrameIdName, UUID::class.java)
```
</blockquote></details>

:thumbsup: good suggestion, adopted.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 57 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeMiJ8824QwaXIFV-Bn:-NevWgAU6rST2NfEaFb4:bp7lo0n) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/3001f3c2a2ba4ae5e4c9a886815daf9e4954bd2d/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L57)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, good points. However, searching through the codebase there are only two occurrences of `!!` left, so commenting out shouldn't be a burden.
</blockquote></details>

:ok_hand: added comments.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt` line 20 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NeresY168WkHyaRYnGH:-NevX9YD3nqBKqB5iS1r:b-d985ta) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt#L20)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You should list `yarn` as a requirement in the `README.md` file and its version.
</blockquote></details>

:ok_hand:  added, same for node.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt` line 12 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NergsmD50G1BGkGvbgi:-NevY691EgpChCyRa4t_:b-cb9i3m) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd extract the object mapper as a `val` member like this:

```kotlin
private val OBJECT_MAPPER = ObjectMapper()
```
</blockquote></details>

:thumbsup:  moved, but kept the `objectMaper` name: `OBJECT_MAPPER` would go against Kotlin naming conventions and makes ktlint complain. Only constants should be named with caps, and for that this would have to be in the companion object.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt` line 17 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NergR8O0X1uqZNbZOwk:-NevXUE17NhgGhBl4v9_:by7z0ml) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt#L17)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This `createFromString` method is currently not used. Maybe it should removed if you are not going to use it in the future PRs?
</blockquote></details>

Removed, this was a leftover from a different approach. Trivial to add later anyways if needed.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt` line 37 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerffQB1UmNMQ8sLG_-:-NevXZNk2vl9YpcMDDz_:b-oprnb5) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt#L37)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I find it easier to read and view the file when the `companion object` part is at the end of the file. Then it is easier to notice which methods depend on the internal state of the class and where the stateless methods start.

Now, at a quick glance, it looks like all the methods are inside the companion object
</blockquote></details>

:thumbsup: moved, seems to be a common practice but I wasn't aware of this.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 121 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NerhliX3Rc4FEL0CTBh:-NevYQnyBm9jOIO0OyUn:b-hldhyu) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L121)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This file makes heavy use of the `var` keyword, even though the object references are not actually mutated.
</blockquote></details>

Fixed all of these instances, again.


<!-- Sent from Reviewable.io -->

2023-09-22 16:11 UTC, culka reviewed
> Reviewed 1 of 92 files at r1, 3 of 14 files at r2, 2 of 5 files at r3, 64 of 71 files at r4, 5 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 141 of 143 files reviewed, 17 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt` line 32 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NexdQK5CMAIpjgOGGwg:-NexdQK5CMAIpjgOGGwh:bh5sl31) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt#L32)):*
> ```Kotlin
>         }
> 
>         process.waitFor(10, TimeUnit.SECONDS)
> ```

These are helpers for testing so I guess it doesn't matter as much, but `waitFor` returns a success value, maybe at least log an error in case this happens.


<!-- Sent from Reviewable.io -->

2023-09-25 09:17 UTC, jarkkoka requested changes
> Reviewed 2 of 71 files at r4.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: all files reviewed, 26 unresolved discussions (waiting on @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt` line 31 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAWr3R6gPaOAzHt9DO:-NfAWr3R6gPaOAzHt9DP:b-tyvts9) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt#L31)):*
> ```Kotlin
> @AutoConfigureMockMvc
> @SpringBootTest
> class TimetablesReplaceApiTest(@Autowired val mockMvc: MockMvc) {
> ```

Pretty neat tests! :+1: 
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt` line 35 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAUotqESh-yAXyuv1t:-NfAUotqESh-yAXyuv1u:b7eikou) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt#L35)):*
> ```Kotlin
>     private lateinit var replaceTimetablesService: ReplaceTimetablesService
> 
>     private val mapper = ObjectMapper()
> ```

I'd move this into the companion object.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt` line 41 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAV9LEC_hYA6q7hAMY:-NfAV9LEC_hYA6q7hAMZ:b-dgkoon) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt#L41)):*
> ```Kotlin
>         UUID.fromString("83e04376-81c7-4b83-8301-a5c9ee253014")
>     )
>     private val targetPriority = TimetablesPriority.STANDARD
> ```

IMO this could be moved to the companion object and renamed to `DEFAULT_TARGET PRIORITY`.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt` line 121 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAW4dT-FlqZzcfGSwW:-NfAW4dT-FlqZzcfGSwX:bd80bhc) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt#L121)):*
> ```Kotlin
>     @Test
>     fun `throws a 404 error when the service fails because the staging frame can not be found`() {
>         val errorMessage = "Staging vehicle schedule frame not found"
> ```

IMO there is no benefit to having this assigned to a variable. Could be just hard-coded inside the expected output message.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 31 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAc6KF-gZb0kPw4nIQ:-NfAc6KF-gZb0kPw4nIR:b-p37me7) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L31)):*
> ```Kotlin
> 
> @SpringBootTest
> class ReplaceTimetablesServiceTest @Autowired constructor(
> ```

well thought out tests :+1: 
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 214 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAZYs23IlMZ_nnc0qR:-NfAZYs23IlMZ_nnc0qS:b-8dfxj7) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L214)):*
> ```Kotlin
>             @Test
>             fun `expires the replaced vehicle schedule frame`() {
>                 val replacedFrame = fetchSingleFrameById(replacedFrameId)
> ```

For a code reader, it would be beneficial to see what the type is.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 219 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAZ8vuDShrYsqFE8PB:-NfAZ8vv9Ukn-eW6Hr9l:b-c4icdh) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L219)):*
> ```Kotlin
>                 val expectedReplacedFrame = initialReplacedFrame
>                 // Ends exactly one day before the new one starts.
>                 assertEquals(initialStagingFrame.validityStart, LocalDate.parse("2023-01-01"))
> ```

The operands appear to be in wrong order. Expected value should be first.

In addition, I'd usually opt to use static typing in form of `LocalDate.of(2023, 1, 1)` instead of parsing `String`s.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 227 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAZggJAEBdkHE3MZEm:-NfAZggJAEBdkHE3MZEn:b-6uljf1) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L227)):*
> ```Kotlin
>             @Test
>             fun `promotes staging timetable to target priority`() {
>                 val stagingFrame = fetchSingleFrameById(stagingFrameId)
> ```

I'd like to see the type here as well.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 269 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAZuUq4s5jWnkGDVPb:-NfAZuUq4s5jWnkGDVPc:bn4ufl0) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L269)):*
> ```Kotlin
> 
>                 assertEquals(replacedFrame1.validityEnd, LocalDate.parse("2022-11-30"))
>                 assertEquals(replacedFrame2.validityEnd, LocalDate.parse("2022-11-30"))
> ```

`LocalDate.parse` method is not being tested here. In other words, the operands appear to be wrong order. It may be a matter of test, but I would use `LocalDate.of(2022, 11, 30)` syntax here in order to minimise risk of having the date in wrong string format.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 280 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfA_pc3Ac_fCPyPcKr6:-NfA_pc3Ac_fCPyPcKr7:bp7k4yu) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L280)):*
> ```Kotlin
>             val stagingFrameId = UUID.fromString("77fa8187-9a8e-4ce6-9fe2-5855f438b0e2")
> 
>             val exception = assertThrows(InvalidTargetPriorityException::class.java) {
> ```

Use Kotlin's `assertFailsWith` instead of `assertThrows` so you don't need to feed a Java class in.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 297 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAa-zZDFPi4rAqi6aM:-NfAa-zZDFPi4rAqi6aN:b2f1r1i) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L297)):*
> ```Kotlin
>             val nonexistentStagingFrameId = UUID.fromString("DEADBEEF-FEED-C0DE-F00D-ABBA1234ABBA")
> 
>             assertThrows(StagingVehicleScheduleFrameNotFoundException::class.java) {
> ```

`assertFailsWith`
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 314 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAa2FeBetVNVmdhue8:-NfAa2FeBetVNVmdhue9:b2f1r1i) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timeta [...]

2023-09-25 10:15 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: all files reviewed, 25 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt` line 32 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NexdQK5CMAIpjgOGGwg:-NfAolIi1eo26OYj-9hV:b910py9) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/main/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt#L32)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

These are helpers for testing so I guess it doesn't matter as much, but `waitFor` returns a success value, maybe at least log an error in case this happens.
</blockquote></details>

:thumbsup:  added a throw in case this times out.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt` line 41 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAV9LEC_hYA6q7hAMY:-NfAjMux8ZTo7fmVp-sM:bfzmdwu) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt#L41)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO this could be moved to the companion object and renamed to `DEFAULT_TARGET PRIORITY`.
</blockquote></details>

I would rather not. Currently you can see the whole default situation in one place at a glance (default inputs and the output), moving some of these would disrupt that. And moving all of them wouldn't help test clarity either in my opinion.

Discussed this in person. Didn't move, but added `default` prefixes to the variables and refactored `executeReplaceTimetablesRequest` calls.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt` line 121 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAW4dT-FlqZzcfGSwW:-NfAdqFn7SfgcwT4Ilbt:bp9cwd0) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt#L121)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO there is no benefit to having this assigned to a variable. Could be just hard-coded inside the expected output message.
</blockquote></details>

This is used in two places, I'd rather put such things in a variable rather than copypasting, even if trivial.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 214 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAZYs23IlMZ_nnc0qR:-NfAg7M3589JJa8-gzsg:b-g01td3) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L214)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

For a code reader, it would be beneficial to see what the type is.
</blockquote></details>

I don't agree with this. IDE already shows the type on hover, and the variable / function names convey the type clearly enough as well.

Also, Kotlin coding conventions states that types should not be included "just for clarity" when they can be left out: https://kotlinlang.org/docs/coding-conventions.html#avoid-redundant-constructs
We've had similar practice on typescript side as well, I think.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 219 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAZ8vuDShrYsqFE8PB:-NfAhy0B1vkNPAKP-NiP:b-i7m2gp) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L219)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The operands appear to be in wrong order. Expected value should be first.

In addition, I'd usually opt to use static typing in form of `LocalDate.of(2023, 1, 1)` instead of parsing `String`s.
</blockquote></details>

Good point, fixed both issues.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 280 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfA_pc3Ac_fCPyPcKr6:-NfAeygc7l7dhg8Y-vHz:b-xeuz5r) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L280)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Use Kotlin's `assertFailsWith` instead of `assertThrows` so you don't need to feed a Java class in.
</blockquote></details>

:thumbsup: good to know!


<!-- Sent from Reviewable.io -->

2023-09-25 11:43 UTC, culka reviewed
> Reviewed 11 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: all files reviewed, 26 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`development.sh` line 51 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfB7i8472aQ3cE0LnoB:-NfB7i8472aQ3cE0LnoC:bn97o7h) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/f2bd2f16001ba1f849df068a008de077694e2af2/development.sh#L51)):*
> ```Shell
> 
> prepare_timetables_data_inserter() {
>   cd jore4-hasura/test/hasura
> ```

Something along the lines of
```
if [ ! -d jore4-hasura/test ]; then
    git submodule init
    git submodule upate
    cd jore4-hasura
    git sparse-checkout init --cone
    git sparse-checkout set test/hasura
    cd ..
fi
```

would be nice here, no need to manually set up the submodule at all


<!-- Sent from Reviewable.io -->

2023-09-25 11:53 UTC, jarkkoka approved these changes
> Reviewed 10 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: all files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt` line 12 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NergsmD50G1BGkGvbgi:-NfB3cWJDENdwjnL8fQI:b2nhll9) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt#L12)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

:thumbsup:  moved, but kept the `objectMaper` name: `OBJECT_MAPPER` would go against Kotlin naming conventions and makes ktlint complain. Only constants should be named with caps, and for that this would have to be in the companion object.
</blockquote></details>

Ok.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 214 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfAZYs23IlMZ_nnc0qR:-NfB3tfB-waL5RgTnNmA:bgw2c5p) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/8ebb72a07ca05a29f16d237023c0910c05b9f6c8/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L214)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I don't agree with this. IDE already shows the type on hover, and the variable / function names convey the type clearly enough as well.

Also, Kotlin coding conventions states that types should not be included "just for clarity" when they can be left out: https://kotlinlang.org/docs/coding-conventions.html#avoid-redundant-constructs
We've had similar practice on typescript side as well, I think.
</blockquote></details>

But Reviewable does not show the types when hovering. :) Not a big deal though.


<!-- Sent from Reviewable.io -->

2023-09-25 11:58 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: 142 of 144 files reviewed, 2 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`development.sh` line 51 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3#-NfB7i8472aQ3cE0LnoB:-NfBC3pWCT0l-mEkpcQL:b3qcs46) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/f2bd2f16001ba1f849df068a008de077694e2af2/development.sh#L51)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Something along the lines of
```
if [ ! -d jore4-hasura/test ]; then
    git submodule init
    git submodule upate
    cd jore4-hasura
    git sparse-checkout init --cone
    git sparse-checkout set test/hasura
    cd ..
fi
```

would be nice here, no need to manually set up the submodule at all
</blockquote></details>

Added. Also included submodule update to this.


<!-- Sent from Reviewable.io -->

2023-09-25 12:45 UTC, culka approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/3)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)



<!-- Sent from Reviewable.io -->

2023-09-28 05:44 UTC, merged