WIP: Add /timetables/combine API
HSLdevcom/jore4-timetables-api pull request #6
Opened 2023-09-26 18:16 UTC by Leitsi

2023-09-28 09:25 UTC, jarkkoka requested changes
> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 3 of 11 files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 118 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfQ3dqw7w0s4FuWWX9C:-NfQ3dqw7w0s4FuWWX9D:b-nk3qoo) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/063cfd2068f4adf141d29b40609dd024bfc480f3/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L118)):*
> ```Kotlin
>             .select()
>             .from(VehicleScheduleFrameTable.VEHICLE_SCHEDULE_FRAME)
>             .where(
> ```

It would be more readable for me if these 4 lines were condensed into one line (since it's just one simple SQL predicate).
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 125 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfQ4Adr90oBM0n05iTb:-NfQ4Adr90oBM0n05iTc:bpb948z) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/063cfd2068f4adf141d29b40609dd024bfc480f3/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L125)):*
> ```Kotlin
>             .and(
>                 VehicleScheduleFrameTable.VEHICLE_SCHEDULE_FRAME.VALIDITY_START
>                     .eq(stagingVehicleScheduleFrame.validityStart)
> ```

Actually, each of these WHERE predicates could be condensed into single line if you static-imported all these items from `VehicleScheduleFrame.Companion` object. <Opt> + <Enter> in IDEA in macOS. 

I mean adding the following import:
```kotlin
import fi.hsl.jore.jore4.jooq.vehicle\_schedule.tables.VehicleScheduleFrame.Companion.VEHICLE\_SCHEDULE\_FRAME
```

The problem now is that these statically typed jOOQ queries are excessively long compared to raw SQL. Therefore, I would do everything possible to make these queries more readable to better understand the processing logic.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleServiceRepository.kt` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfQ55Va-zD9YN2Ehmkp:-NfQ55Va-zD9YN2Ehmkq:bruoq3p) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/063cfd2068f4adf141d29b40609dd024bfc480f3/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleServiceRepository.kt#L13)):*
> ```Kotlin
> @Repository
> class VehicleServiceRepository(private val dsl: DSLContext, config: DefaultConfiguration) : VehicleServiceDao(config) {
>     @Transactional(noRollbackFor = [RuntimeException::class])
> ```

You should add mandatory propagation here as well like you did in a another repository.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleServiceRepository.kt` line 17 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfQ5_BJ6PenlW6oQBpw:-NfQ5_BJ6PenlW6oQBpx:b-irwbir) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/063cfd2068f4adf141d29b40609dd024bfc480f3/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleServiceRepository.kt#L17)):*
> ```Kotlin
>         return dsl.update(VehicleServiceTable.VEHICLE_SERVICE_)
>             .set(
>                 VehicleServiceTable.VEHICLE_SERVICE_.VEHICLE_SCHEDULE_FRAME_ID,
> ```

I would statically import `VEHICLE_SERVICE_` here as well to make these more condensed. Like below:

```kotlin
    return dsl.update(VEHICLE_SERVICE_)  
        .set(VEHICLE_SERVICE_.VEHICLE_SCHEDULE_FRAME_ID, newFrameId)  
        .where(VEHICLE_SERVICE_.VEHICLE_SCHEDULE_FRAME_ID.eq(currentFrameId))  
        .execute()
```


<!-- Sent from Reviewable.io -->

2023-09-28 09:28 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 3 of 11 files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 125 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfQ4Adr90oBM0n05iTb:-NfQ6JrtE_wFj9YJSW_a:bmux54p) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/063cfd2068f4adf141d29b40609dd024bfc480f3/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L125)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Actually, each of these WHERE predicates could be condensed into single line if you static-imported all these items from `VehicleScheduleFrame.Companion` object. <Opt> + <Enter> in IDEA in macOS. 

I mean adding the following import:
```kotlin
import fi.hsl.jore.jore4.jooq.vehicle\_schedule.tables.VehicleScheduleFrame.Companion.VEHICLE\_SCHEDULE\_FRAME
```

The problem now is that these statically typed jOOQ queries are excessively long compared to raw SQL. Therefore, I would do everything possible to make these queries more readable to better understand the processing logic.
</blockquote></details>

Meant to say Opt (key) + Enter (key) in macOS. Something wierd is happening in formatting comments...


<!-- Sent from Reviewable.io -->

2023-09-28 09:59 UTC, culka requested changes
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 5 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 46 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfQ6UW00c1a3zIBG1Dq:-NfQ6UW10ucMBvd602UV:bfg35gt) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/063cfd2068f4adf141d29b40609dd024bfc480f3/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L46)):*
> ```Kotlin
>     )
> 
>     @PostMapping("combine")
> ```

New REST interfaces should be documented in the readme.


<!-- Sent from Reviewable.io -->

2023-09-28 10:44 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 5 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 118 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfQ3dqw7w0s4FuWWX9C:-NfQNkKY2OEO5DOpTUxq:b4ujnx2) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/063cfd2068f4adf141d29b40609dd024bfc480f3/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L118)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It would be more readable for me if these 4 lines were condensed into one line (since it's just one simple SQL predicate).
</blockquote></details>

Lines were too long so Idea's formatter splits them like this. But after importing VEHICLE_SCHEDULE_FRAME from companion object these fit on one line.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt` line 125 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfQ4Adr90oBM0n05iTb:-NfQNLc62FMnvjLnHd-Z:b-fznogt) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/063cfd2068f4adf141d29b40609dd024bfc480f3/src/main/kotlin/fi/hsl/jore4/timetables/repository/VehicleScheduleFrameRepository.kt#L125)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Meant to say Opt (key) + Enter (key) in macOS. Something wierd is happening in formatting comments...
</blockquote></details>

Good idea, done.


<!-- Sent from Reviewable.io -->

2023-09-29 06:38 UTC, jarkkoka requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 41 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUdRpd9es2RU_dLmOs:-NfUdRpd9es2RU_dLmOt:b-im8obe) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L41)):*
> ```Kotlin
> 
>     // This is currently not used from outside this service, only exposed for testing.
>     @Transactional(noRollbackFor = [RuntimeException::class])
> ```

IMO `noRollback` attribute should be removed because:
- because it is ineffective during application runtime because this method is only called internally, which is why the call does not cycle through the proxy object dynamically created by Spring
- In tests rollbacks should occur in order to verify correct results


<!-- Sent from Reviewable.io -->

2023-09-29 06:45 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 84 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUfeWJAPCBw_xCXWH_:-NfUfeWK4nveyxUILmd6:b-2dejjm) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L84)):*
> ```Kotlin
>         val stagingFrame =
>             vehicleScheduleFrameRepository.fetchOneByVehicleScheduleFrameId(stagingVehicleScheduleFrameId)
>         if (stagingFrame != null && stagingFrame.priority == TimetablesPriority.STAGING.value) {
> ```

I guess Kotlin-idiomatic way of writing this is chaining calls like this:

```kotlin
return vehicleScheduleFrameRepository  
    .fetchOneByVehicleScheduleFrameId(stagingVehicleScheduleFrameId)  
    ?.takeIf {  
        it.priority == TimetablesPriority.STAGING.value  
    }  
    ?: throw StagingVehicleScheduleFrameNotFoundException(  
        "Staging vehicle schedule frame not found",  
        stagingVehicleScheduleFrameId  
    )
```


<!-- Sent from Reviewable.io -->

2023-09-29 06:50 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 84 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUfeWJAPCBw_xCXWH_:-NfUg_QT-kehOYFhW9rG:b5xlz7m) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L84)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I guess Kotlin-idiomatic way of writing this is chaining calls like this:

```kotlin
return vehicleScheduleFrameRepository  
    .fetchOneByVehicleScheduleFrameId(stagingVehicleScheduleFrameId)  
    ?.takeIf {  
        it.priority == TimetablesPriority.STAGING.value  
    }  
    ?: throw StagingVehicleScheduleFrameNotFoundException(  
        "Staging vehicle schedule frame not found",  
        stagingVehicleScheduleFrameId  
    )
```
</blockquote></details>

For me the above condensed version is easier to reason about.

It contains a single expression without unnecessary variable declarations and it is easy to see that there are no mutations.


<!-- Sent from Reviewable.io -->

2023-09-29 07:07 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 5 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 67 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUj4Oq9e0bYifkR_zX:-NfUj4Oq9e0bYifkR_zY:b-i6ub1n) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L67)):*
> ```Kotlin
> 
>         // TODO: ensure that there are no identical journeys in staging and target.
>         // DB triggers do not ensure this.
> ```

I like these TODO comments being left here for future reference.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 80 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUkjRT380aERbfUUkN:-NfUkjRT380aERbfUUkO:by5urut) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L80)):*
> ```Kotlin
>             every {
>                 combineTimetablesServiceMock.combineSingleTimetable(
>                     stagingFrameIds[0],
> ```

I guess a loop would work here to reduce code duplication:

```kotlin
stagingFrameIds.zip(targetFrameIds).forEach { (stagingFrameId, targetFrameId) ->  
    every {  
        combineTimetablesServiceMock.combineSingleTimetable(  
            stagingFrameId,  
            TimetablesPriority.STANDARD  
        )  
    } returns targetFrameId  
}```
```



<!-- Sent from Reviewable.io -->

2023-09-29 07:09 UTC, jarkkoka requested changes
I'm (once again) amazed at how well you can write tests.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-:-NfUlJb81zlh5JC6kkDF:b-t3ku7u)* status: 4 of 11 files reviewed, 6 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 156 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUl70F4G69lbFChinp:-NfUl70F4G69lbFChinq:b-2bktpe) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L156)):*
> ```Kotlin
>             verify(exactly = 1) {
>                 combineTimetablesServiceMock.combineSingleTimetable(
>                     stagingFrameIds[0],
> ```

Maybe these could as well be done in a loop.

There are other cases as well in this file where loops could work...


<!-- Sent from Reviewable.io -->

2023-09-29 07:32 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 7 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 104 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUq2Ze2ef0KuV3JIH5:-NfUq2Ze2ef0KuV3JIH6:b-wrbvza) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L104)):*
> ```Kotlin
> 
>             verify(exactly = 1) {
>                 combineTimetablesServiceMock.combineSingleTimetable(
> ```

For me, as a reviewer, when I see that code construction is repeated, the first question that comes to mind is how the individual statements differ from each other in such a way that a loop cannot be used. In other words, the logical assumption is that a loop is used whenever possible.


<!-- Sent from Reviewable.io -->

2023-09-29 08:39 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 10 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 31 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfV2aA4-yGt3Zn6_ugR:-NfV2aA4-yGt3Zn6_ugS:b8rzb0e) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L31)):*
> ```Kotlin
> import kotlin.test.assertNull
> 
> private val LOGGER = KotlinLogging.logger {}
> ```

ATM `LOGGER` not used, subject for removal
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 51 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfV30Wk0wlOxst8DYQM:-NfV30Wk0wlOxst8DYQN:b-fa4tr8) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L51)):*
> ```Kotlin
>     @MockKExtension.ConfirmVerification
>     @DisplayName("combineTimetables")
>     class CombineTimetables {
> ```

Should be `inner class` instead of just `class`. Now the tests are not executed by Maven surefire plugin!!
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 47 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfV4aAh9--hFRyZkrl7:-NfV4aAh9--hFRyZkrl8:b9ngk1k) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L47)):*
> ```Kotlin
>     @MockKExtension.ConfirmVerification
>     @DisplayName("replaceTimetables")
>     class ReplaceTimetables {
> ```

Should be `inner class` instead of just `class`. Now the tests are not executed by Maven surefire plugin!!

Unfortunately, this has been missed in the previous review.


<!-- Sent from Reviewable.io -->

2023-09-30 13:47 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 4 of 11 files reviewed, 10 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt` line 41 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUdRpd9es2RU_dLmOs:-Nfa4P1X54hQzZnJY7rf:b-u76ti6) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/main/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesService.kt#L41)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `noRollback` attribute should be removed because:
- because it is ineffective during application runtime because this method is only called internally, which is why the call does not cycle through the proxy object dynamically created by Spring
- In tests rollbacks should occur in order to verify correct results
</blockquote></details>

Removed. Also removed from similar method in ReplaceTimetablesService since the situation is identical.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 80 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUkjRT380aERbfUUkN:-NfaAFlC278teL1gHgc-:b-whxg2g) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L80)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I guess a loop would work here to reduce code duplication:

```kotlin
stagingFrameIds.zip(targetFrameIds).forEach { (stagingFrameId, targetFrameId) ->  
    every {  
        combineTimetablesServiceMock.combineSingleTimetable(  
            stagingFrameId,  
            TimetablesPriority.STANDARD  
        )  
    } returns targetFrameId  
}```
```

</blockquote></details>

Implemented something like this. Now same lambdas can be used for setting up the return values and performing the verifys.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 104 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUq2Ze2ef0KuV3JIH5:-Nfa910YCj_R6F9gEGRG:bujd3nl) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L104)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

For me, as a reviewer, when I see that code construction is repeated, the first question that comes to mind is how the individual statements differ from each other in such a way that a loop cannot be used. In other words, the logical assumption is that a loop is used whenever possible.
</blockquote></details>

I quite dislike using loops for assertions, since they make debugging possible failures more difficult: if the loop throws an error, it is no longer enough to figure out what line from the test failed, but you also need to know the iteration of the loop. Thus I rather repeat the verifications, or use some other structure for asserting all calls at once (which I haven't figured out yet how to do in Kotlin).

But in this case there's way too much boilerplate. Refactored a bit and managed to reduce the lines of code in these to tests by about half.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 156 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUl70F4G69lbFChinp:-Nfa9nJZ0cGxGf1blKch:b-jzf7fg) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L156)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Maybe these could as well be done in a loop.

There are other cases as well in this file where loops could work...
</blockquote></details>

Did a similar refactoring here.


<!-- Sent from Reviewable.io -->

2023-10-03 07:33 UTC, jarkkoka requested changes
> Reviewed 2 of 11 files at r1, 2 of 5 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: all files reviewed, 11 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`README.md` line 54 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoCYQt2JEWNfL-zyWw:-NfoCYQt2JEWNfL-zyWx:b-8welnq) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/README.md#L54)):*
> ```Markdown
>     ],
>     // The priority to which the staging timetables will be promoted.
>     // Timetables priority, eg. STANDARD = 10
> ```

"e.g." is grammatically correct
___
*[`README.md` line 80 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoC_ru-AxdqR7MsXMV:-NfoC_ru-AxdqR7MsXMW:b-8welnq) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/README.md#L80)):*
> ```Markdown
>     ],
>     // The priority to which the staging timetables will be promoted.
>     // Timetables priority, eg. STANDARD = 10
> ```

"e.g." is grammatically correct
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/HelloWorldTest.kt` line 16 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoDj1MEot2ePvKV8gv:-NfoDj1MEot2ePvKV8gw:b-sfhhr6) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/api/HelloWorldTest.kt#L16)):*
> ```Kotlin
> @DisplayName("Test Hello World API")
> @MockKExtension.ConfirmVerification
> class HelloWorldTest {
> ```

This class can later be removed in a separate PR now that there are test classes that contain actual integration tests.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/extensions/TimetablesDatasetExtensions.kt` line 14 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoF7oICGQ92Ddf92gW:-NfoF7oICGQ92Ddf92gX:b-vmlmc1) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/extensions/TimetablesDatasetExtensions.kt#L14)):*
> ```Kotlin
>         LOGGER.debug { "Get path: $childPath" }
>         if (childPath !in child) {
>             throw RuntimeException("No child item found at property '$childPath'")
> ```

I'd put `IllegalStateException` instead here. Not a big deal though.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 104 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUq2Ze2ef0KuV3JIH5:-NfoGiMU5Ot5BtXzYbB0:b-qpfrrg) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L104)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I quite dislike using loops for assertions, since they make debugging possible failures more difficult: if the loop throws an error, it is no longer enough to figure out what line from the test failed, but you also need to know the iteration of the loop. Thus I rather repeat the verifications, or use some other structure for asserting all calls at once (which I haven't figured out yet how to do in Kotlin).

But in this case there's way too much boilerplate. Refactored a bit and managed to reduce the lines of code in these to tests by about half.
</blockquote></details>

Okay. This is now much less burdensome to read.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 156 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfUl70F4G69lbFChinp:-NfoNKGb5P0s-YpHSV9k:b-83sjo4) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/110ad66b9bd26608cb362c7f3727c4516295fc31/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L156)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Did a similar refactoring here.
</blockquote></details>

Nice.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 103 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoN4B-0E16AjEpKCr6:-NfoN4B-0E16AjEpKCr7:b-a04f13) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L103)):*
> ```Kotlin
> 
>         @Test
>         fun `fails if any of the requested staging frames do not get handled successfully`() {
> ```

This test case lacks verifying the state of the database after execution. Interaction with other classes/object is tested (unit test part), but not the result of the operation in the database (integration test part).

Getting an exception does not guarantee that all changes have been rolled back. From the verified interactions that have taken place, we can see that database operations may have taken place. Based on this test, we are now not sure if any changes were persisted to the database, i.e. whether the transaction context handling is working as expected.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 129 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoNPMvDOg9ff4DIw_Q:-NfoNPMvDOg9ff4DIw_R:b-32680w) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L129)):*
> ```Kotlin
>         @Nested
>         @DisplayName("when successfully combining a single new vehicle journey")
>         inner class WhenSuccessfullyCombiningSingleNewVehicleJourney {
> ```

I see you are performing real integration tests here. :+1: 
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 358 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoQbtf46mG9VNOmmoq:-NfoQbtf46mG9VNOmmor:bgjjuz) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L358)):*
> ```Kotlin
>             targetVehicleJourneys = mutableMapOf(
>                 // Identical vehicle journey as the one about to come from staging -> fail.
>                 "route123Outbound1" to stagingVehicleJourneys["route123Outbound1"],
> ```

This method would be more readable without `var` variables.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 368 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoQxwX3jIsToeSIMq6:-NfoQxwX3jIsToeSIMq7:b-yd7ohr) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L368)):*
> ```Kotlin
>             timetablesDataInserterRunner.runTimetablesDataInserter(testData.toJSONString())
> 
>             // FIXME: this should fail.
> ```

So is there a bug that needs to be fixed?
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 89 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoRp356F6KBAV87tZw:-NfoRp356F6KBAV87tZx:bp4w6jc) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt#L89)):*
> ```Kotlin
>             every { mockProcessSingleCalls[0]() } returns listOf(replacedFrameIds[0])
>             every { mockProcessSingleCalls[1]() } returns emptyList()
>             every { mockProcessSingleCalls[2]() } returns listOf(
> ```

This is more pleasant to read now! :+1: 

 [...]

2023-10-03 17:23 UTC, jarkkoka requested changes
> Reviewed 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 103 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoN4B-0E16AjEpKCr6:-NfqXfeIAKJGhRE9r9BX:b-9z1il1) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L103)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not possible with this current mock setup, since nothing is actually persisted to database here.

As I've understood it, doesn't Spring automatically roll back transactions on `RuntimeException`s, by default?

Transactions being rolled back are tested in `combineSingleTimetable` tests (maybe some checks are lacking, will add some more checks there). Though, directly for this `combineTimetables` there are no such tests, true.

Adding those would basically mean removing the mock setup and replacing that with real data, which might get quite verbose since we need multiple frames. Or using some combination of those: add real data for the first item and mock the rest.

Alternatively, could just remove the single method and test everything via the main public method. That would make testing these "how multiple frames are handled" cases more burdensome since mocks basically can't be used.
</blockquote></details>

Yes, you are correct that, by default, Spring rolls back transaction in case of `RuntimeException`.

Personally, I feel that integration tests (no mocking) offer more "bang for the buck", especially in the case of the Service layer driving the application business logic. I think it is more important to know the side effects happening in the database than the interaction with other classes/objects. The real database is also involved in the integration tests rather than some idealised vision.

We need to check whether if the Spring configuration is done correctly in terms of transaction management.


<!-- Sent from Reviewable.io -->

2023-10-04 08:43 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 7 of 15 files reviewed, 4 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 103 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoN4B-0E16AjEpKCr6:-NftqZ1S9pll_aY7-q-g:bb3n5yw) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L103)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Yes, you are correct that, by default, Spring rolls back transaction in case of `RuntimeException`.

Personally, I feel that integration tests (no mocking) offer more "bang for the buck", especially in the case of the Service layer driving the application business logic. I think it is more important to know the side effects happening in the database than the interaction with other classes/objects. The real database is also involved in the integration tests rather than some idealised vision.

We need to check whether if the Spring configuration is done correctly in terms of transaction management.
</blockquote></details>

Removed the mocks and added similar tests with real data. Also caught couple of bugs like this, so was worth it. Main issue here was the amount of test data needed.


<!-- Sent from Reviewable.io -->

2023-10-04 08:52 UTC, jarkkoka requested changes
> Reviewed 7 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 13 of 15 files reviewed, 12 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt` line 23 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-Nftfm8x0pbibvL8x3P-:-Nftfm8y6Se_-8lnln-H:bgpvhw) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt#L23)):*
> ```Kotlin
> 
>         fun createFromMutableMap(data: MutableMap<String, Any?>): TimetablesDataset {
>             var timetablesDataset = TimetablesDataset()
> ```

The object reference is not mutated => replace `var` with `val`
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 368 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoQxwX3jIsToeSIMq6:-Nftg0Ul64hry88eCB0t:b3r1nnn) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L368)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Yep, this is related to the TODO comment on the service. Doesn't work correctly in this case at the moment.
There is a separate for this issue so fixing is not part of this PR, but thought I'd put a "placeholder" test already.
</blockquote></details>

Ok, thanks for clarification.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 53 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftgVts6m4r0-mKaSCS:-NftgVts6m4r0-mKaSCT:b-rmj9sk) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L53)):*
> ```Kotlin
>             fun runCombineSingleTimetable() {
>                 val testData = TimetablesDataset.createFromResource("datasets/combine.json")
>                 timetablesDataInserterRunner.runTimetablesDataInserter(testData.toJSONString())
> ```

You can't really tell from the code whether the database tables (involved in the tests) are truncated by this `timetablesDataInserterRunner` call before inserting data. Am I correct in assuming this will happen? If yes, please add a comment about this matter.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 123 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftiLpx4KJsJaqLzyI_:-NftiLpx4KJsJaqLzyIa:b320rij) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L123)):*
> ```Kotlin
>             assertContains(exception.message.toString(), "Can not set priority STAGING as target.")
> 
>             assertEquals(initialStagingFrame, fetchSingleFrameById(stagingFrameId))
> ```

For better test coverage, I'd also test that:
- the number of frames having `STANDARD` priority has not changed
- the target frame has not changed either
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 157 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-Nftizvw7TlqHWGbgGrE:-Nftizvw7TlqHWGbgGrF:b320rij) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L157)):*
> ```Kotlin
>                 )
>             }
>             assertEquals(initialNonStagingFrame, fetchSingleFrameById(nonStagingFrameId))
> ```

For better test coverage, I'd also test that:
- the number of frames having `STANDARD` priority has not changed
- the target frame has not changed either
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 262 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftrpZoBZDW2fC1FSrb:-NftrpZoBZDW2fC1FSrc:b-4b0bj8) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L262)):*
> ```Kotlin
>             }
>             assertEquals(exception.stagingVehicleScheduleFrameId, stagingFrameId)
>             assertThat(exception.targetVehicleScheduleFrameIds).containsExactlyInAnyOrder(
> ```

Bad code style to mix traditional JUnit assertions with AssertJ assertions. AssertJ itself is fine.

It would have been better to start from scratch with AssertJ, if need be.

This could also be written as:

```kotlin
assertEquals(exception.targetVehicleScheduleFrameIds.toSet(), setOf(target1FrameId,target2FrameId))
```
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 409 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftpDa91sxMMvTXn23S:-NftpDa91sxMMvTXn23T:b-nu9k6m) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L409)):*
> ```Kotlin
>             // Each staging frame got processed: old frames deleted.
>             assertNull(vehicleScheduleFrameRepository.fetchOneByVehicleScheduleFrameId(stagingFrameIds[0]))
>             assertNull(vehicleScheduleFrameRepository.fetchOneByVehicleScheduleFrameId(stagingFrameIds[1]))
> ```

Here it is not verified that each source frame is associated with a correct target frame. As a reviewer, I consider it possible that the source frames can be wrongly mixed with target frames. What do you think about this?
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 419 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftoJPtA9XwTZInzOEe:-NftoJPtA9XwTZInzOEf:botktdc) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L419)):*
> ```Kotlin
>             timetablesDataInserterRunner.runTimetablesDataInserter(testData.toJSONString())
> 
>             val initialFrames = vehicleScheduleFrameRepository.findAll().sortedBy { it.label }
> ```

If you converted these collections into sets (by appending `.toSet()` instead of `.sortedBy { ... }`) then you wouldn't need to sort them. However, `List` is fine for me. At least, the (maybe theoretically possible?) duplicates would be caught when not using `Set`s.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 434 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-Nftn4fiA9a4qN4SCFJK:-Nftn4fiA9a4qN4SCFJL:b-ed3pko) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L434)):*
> ```Kotlin
>             val servicesAfter = vehicleServiceRepository.findAll().sortedBy { it.vehicleServiceId }
>             assertEquals(initialFrames, framesAfter)
>             assertEquals(initialServices, servicesAfter)
> ```

You rely on the implementation of the `equals` method in the generated `VehicleScheduleFrame` and `VehiceService` classes. In fact, they are data classes with a custom implementation of the `equals` method.

Based on what I saw of them from a quick glance, I assume these assertions are sufficient.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesServiceTest.kt` line 38 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-Nftk1HK8Rf5HQUWlaTb:-Nftk1HK8Rf5HQUWlaTc:b6aa6wx) ([raw file](ht [...]

2023-10-04 08:58 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 13 of 15 files reviewed, 12 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 262 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftrpZoBZDW2fC1FSrb:-Nftu5WEEQq_sqQcut2f:b-sq723m) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L262)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Bad code style to mix traditional JUnit assertions with AssertJ assertions. AssertJ itself is fine.

It would have been better to start from scratch with AssertJ, if need be.

This could also be written as:

```kotlin
assertEquals(exception.targetVehicleScheduleFrameIds.toSet(), setOf(target1FrameId,target2FrameId))
```
</blockquote></details>

Sorry, put the operands in wrong order (JUnit vs AssertJ confusion)

```kotlin
assertEquals(setOf(target1FrameId ,target2FrameId), exception.targetVehicleScheduleFrameIds.toSet())
```


<!-- Sent from Reviewable.io -->

2023-10-04 09:11 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 13 of 15 files reviewed, 11 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 103 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfoN4B-0E16AjEpKCr6:-Nftwv2NDlBEiyWr0AGg:b-hgugez) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c0b54cac521d6f50ed409ea16682e8e4b2d257f1/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L103)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Removed the mocks and added similar tests with real data. Also caught couple of bugs like this, so was worth it. Main issue here was the amount of test data needed.
</blockquote></details>

Very good! :+1: 


<!-- Sent from Reviewable.io -->

2023-10-04 09:14 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 13 of 15 files reviewed, 10 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt` line 23 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-Nftfm8x0pbibvL8x3P-:-NftxZKq13fkL7LeRjr5:b-he4a1z) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The object reference is not mutated => replace `var` with `val`
</blockquote></details>

This method could also be written (more concisely) as:

```kotlin
fun createFromMutableMap(data: MutableMap<String, Any?>) = TimetablesDataset().also { it.putAll(data) }
```


<!-- Sent from Reviewable.io -->

2023-10-04 10:17 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 13 of 15 files reviewed, 10 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt` line 23 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-Nftfm8x0pbibvL8x3P-:-Nfu0f3K3NfMRlkR8NJo:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/TimetablesDataset.kt#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This method could also be written (more concisely) as:

```kotlin
fun createFromMutableMap(data: MutableMap<String, Any?>) = TimetablesDataset().also { it.putAll(data) }
```
</blockquote></details>

:+1: 
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 53 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftgVts6m4r0-mKaSCS:-Nfu-Ov18BQLl_IY3ahB:btaq4km) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L53)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You can't really tell from the code whether the database tables (involved in the tests) are truncated by this `timetablesDataInserterRunner` call before inserting data. Am I correct in assuming this will happen? If yes, please add a comment about this matter.
</blockquote></details>

Yep, currently the inserter truncates the whole DB before inserting.

I'll maybe just rename this method.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 262 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftrpZoBZDW2fC1FSrb:-NftvmOe62hvcCIvlC6Q:btlgetw) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L262)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Sorry, put the operands in wrong order (JUnit vs AssertJ confusion)

```kotlin
assertEquals(setOf(target1FrameId ,target2FrameId), exception.targetVehicleScheduleFrameIds.toSet())
```
</blockquote></details>

:thumbsup: good suggestion, wasn't sure how to achieve this with jUnit assertions.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 409 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftpDa91sxMMvTXn23S:-Nftxw5r64gm2XX2hDd-:bxmoie1) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L409)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Here it is not verified that each source frame is associated with a correct target frame. As a reviewer, I consider it possible that the source frames can be wrongly mixed with target frames. What do you think about this?
</blockquote></details>

Had thought about it but decided not to add.
The main point of these tests is to test what is basically a for loop, that it gets called for each frame as supposed to and returns correct result, and also that the whole transaction either commits or rollbacks. Current checks are enough to verify this. The internal handling of each staging frame do not affect each other, since they are not aware of each other, besides being in same transaction. All the details what happens per staging frame are already more exhaustively tested in other tests, we would basically be just duplicating those here and adding more test code that would obscure the main point here.
If the internals were ever refactored such that each staging frame is more involved with others on the same call, so that this kind of errors were realistic, then this kind of tests would be called for. But  currently I don't think it's necessary or very useful.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 419 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftoJPtA9XwTZInzOEe:-NftwCuF7_-UBNX6nHYh:brzuhk2) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L419)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

If you converted these collections into sets (by appending `.toSet()` instead of `.sortedBy { ... }`) then you wouldn't need to sort them. However, `List` is fine for me. At least, the (maybe theoretically possible?) duplicates would be caught when not using `Set`s.
</blockquote></details>

:ok_hand: changed, since I use toSet elsewhere now as well.


<!-- Sent from Reviewable.io -->

2023-10-04 11:01 UTC, jarkkoka requested changes
> Reviewed 1 of 1 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: all files reviewed, 3 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 409 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NftpDa91sxMMvTXn23S:-NfuDOKQ4b7D_dHmxKwx:b-cv9jz6) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/c6f7826f4cab1b0334e749fbc1485cd64a8707b9/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L409)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Had thought about it but decided not to add.
The main point of these tests is to test what is basically a for loop, that it gets called for each frame as supposed to and returns correct result, and also that the whole transaction either commits or rollbacks. Current checks are enough to verify this. The internal handling of each staging frame do not affect each other, since they are not aware of each other, besides being in same transaction. All the details what happens per staging frame are already more exhaustively tested in other tests, we would basically be just duplicating those here and adding more test code that would obscure the main point here.
If the internals were ever refactored such that each staging frame is more involved with others on the same call, so that this kind of errors were realistic, then this kind of tests would be called for. But  currently I don't think it's necessary or very useful.
</blockquote></details>

Ok, fair enough. Thanks for the clarification.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 135 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfuKiTC7CXRvJhYf4nv:-NfuKiTC7CXRvJhYf4nw:b-c85uss) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7b9ceedc44c3bcc4702200ff5ea4bcc9f6c3509a/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L135)):*
> ```Kotlin
>             assertFailsWith<StagingVehicleScheduleFrameNotFoundException> {
>                 combineTimetablesService.combineTimetables(
>                     listOf(nonexistentStagingFrameId),
> ```

I think additional assertions related to the state of the database after execution should be added into this test case as well.

What do you think?


<!-- Sent from Reviewable.io -->

2023-10-04 11:13 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6)* status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 135 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/6#-NfuKiTC7CXRvJhYf4nv:-NfuNLaSDyZiXVc0b2L2:b-jfqmxs) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7b9ceedc44c3bcc4702200ff5ea4bcc9f6c3509a/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L135)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think additional assertions related to the state of the database after execution should be added into this test case as well.

What do you think?
</blockquote></details>

Didn't add any such expects because there's nothing realistic that could be checked: there's no updates/deletes to be rolled back in this case. But now that we check all frames in other fail tests could add a check here as well, though it feels a bit like paranoid  testing.


<!-- Sent from Reviewable.io -->

2023-10-05 06:35 UTC, merged