Add GET endpoint /toReplace
HSLdevcom/jore4-timetables-api pull request #9
Opened 2023-10-09 11:09 UTC by Perholehto

2023-10-09 12:39 UTC, culka requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Leitsi and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/config/WebSecurityConfig.kt` line 36 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJQeat9a2-ZwlCeBSW:-NgJQeat9a2-ZwlCeBSX:b-ow5rv3) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/config/WebSecurityConfig.kt#L36)):*
> ```Kotlin
>                         "/timetables/*"
>                     ).permitAll()
>                     .requestMatchers(
> ```

This can be combined with the earlier `HttpMethod.GET` list
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 83 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJR4Z65MJJimzq9Ldi:-NgJR4Z65MJJimzq9Ldj:b-fafl4x) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L83)):*
> ```Kotlin
>             TimetablesPriority.fromInt(targetPriority)
>         )
>             .map { frame -> frame.vehicleScheduleFrameId!! }
> ```

No need to name the `frame` variable when it is a simple use case like this. `it` always refers to the element when one is not speciefied.
Like:

`.map { it.vehicleSheduleFrameId!! }`

Also use of `!!` should be avoided when possible, maybe use `.mapNotNull` here?


<!-- Sent from Reviewable.io -->

2023-10-10 05:08 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @culka and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 84 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgMx8wn3hd1nOaJn-LC:-NgMx8wn3hd1nOaJn-LD:b9r69fa) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L84)):*
> ```Kotlin
>     }
> 
>     data class ToReplaceTimetablesResponseBody(
> ```

How are these used in the UI? What's the rationale for not returning the actual VehicleScheduleFrame objects?

Returning whole objects will add some complexity to test side, sure, but this is a very typical case so nothing we shouldn't be able to deal with.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 89 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgMwcxQ8KM7qoo9ZBhM:-NgMwcxQ8KM7qoo9ZBhN:b-nthb75) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L89)):*
> ```Kotlin
> 
>     @GetMapping("toReplace")
>     fun replaced(
> ```

Maybe would be good if function name matched the endpoint mapping?



_Suggestion:_
```Kotlin
    @GetMapping("toReplace")
    fun toReplace(
```
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 190 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJVK5P8tg0LYrAk4_U:-NgJVK5P8tg0LYrAk4_V:b-tzlze7) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L190)):*
> ```Kotlin
>     ) : HasuraErrorExtensions(code)
> 
>     @ExceptionHandler(TargetPriorityParsingException::class)
> ```

Could this exception somehow be used for `isTargetPriorityValid` validation in `CombineOrReplaceTimetablesRequestBody` as well? Currently it throws a very random error and there's some TODO comments about this in the related tests.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 71 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJVyDNBG-9VJDOQpGj:-NgJVyDO0_FMYYcrwHB7:b4r000k) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L71)):*
> ```Kotlin
> 
>     @Transactional(readOnly = true)
>     fun fetchVehicleScheduleFrameIdsToReplace(
> ```

Does this really need a separate method in the service? I would rather call `fetchVehicleScheduleFramesToReplace` directly from the controller. If this method is left here then it should be tested as well, sounds simpler not to have to do that.


<!-- Sent from Reviewable.io -->

2023-10-10 05:40 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @culka and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 88 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgN5KrZ18mcV_ZcRF5T:-NgN5KrZ18mcV_ZcRF5U:b-delpdj) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L88)):*
> ```Kotlin
>     )
> 
>     @GetMapping("toReplace")
> ```

Documentation of the endpoint should be added to README.


<!-- Sent from Reviewable.io -->

2023-10-12 12:22 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 84 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgMx8wn3hd1nOaJn-LC:-NgYGrn_1zTZJ0TZhSo8:b-rpvlbl) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L84)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

How are these used in the UI? What's the rationale for not returning the actual VehicleScheduleFrame objects?

Returning whole objects will add some complexity to test side, sure, but this is a very typical case so nothing we shouldn't be able to deal with.
</blockquote></details>

This was discussed in slack thread and for me it makes more sense to return only IDs, because there is no good way to type return value.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 88 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgN5KrZ18mcV_ZcRF5T:-NgYFeegCmu_BHpfiRtm:b-7awfdm) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L88)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Documentation of the endpoint should be added to README.
</blockquote></details>

Added in a own commit
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 89 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgMwcxQ8KM7qoo9ZBhM:-NgYFojxD_bx4SdxQ9zM:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L89)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Maybe would be good if function name matched the endpoint mapping?
</blockquote></details>

Done
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 190 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJVK5P8tg0LYrAk4_U:-NgYlpHM3pc53yg8qST3:b-xi324l) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L190)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could this exception somehow be used for `isTargetPriorityValid` validation in `CombineOrReplaceTimetablesRequestBody` as well? Currently it throws a very random error and there's some TODO comments about this in the related tests.
</blockquote></details>

I think it's possible that add a custom validation annotation. I tried to add that annotation but didn't succeed. Don't wanna use more time for this now... I think Teemu or Jarkko can solve it in minutes..
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/config/WebSecurityConfig.kt` line 36 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJQeat9a2-ZwlCeBSW:-NgYFsaq757WFSwkc_Hi:bou2vs8) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/config/WebSecurityConfig.kt#L36)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

This can be combined with the earlier `HttpMethod.GET` list
</blockquote></details>

This is now combined
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 71 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJVyDNBG-9VJDOQpGj:-NgYG1E0AJimgQxeTTIW:b-bhr5ph) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L71)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Does this really need a separate method in the service? I would rather call `fetchVehicleScheduleFramesToReplace` directly from the controller. If this method is left here then it should be tested as well, sounds simpler not to have to do that.
</blockquote></details>

Removed this method from the service and logic is moved directly under the controller.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 83 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJR4Z65MJJimzq9Ldi:-NgYFxQDDhmgucSHygng:b-arcnx6) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L83)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

No need to name the `frame` variable when it is a simple use case like this. `it` always refers to the element when one is not speciefied.
Like:

`.map { it.vehicleSheduleFrameId!! }`

Also use of `!!` should be avoided when possible, maybe use `.mapNotNull` here?
</blockquote></details>

This is moved to controller and change to use `.mapNotNull` and `it`


<!-- Sent from Reviewable.io -->

2023-10-12 13:06 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @culka and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 17 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgYxq35BWFagoENNpQz:-NgYxq35BWFagoENNpR-:bwvi9si) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L17)):*
> ```Kotlin
> class StagingVehicleScheduleFrameNotFoundException(message: String, val stagingVehicleScheduleFrameId: UUID) : RuntimeException(message)
> 
> class TargetPriorityParsingException(message: String, val targetPriority: Int) : RuntimeException(message)
> ```

This probably shouldn't be here, not used from this service.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt` line 42 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgYyObl-l6f3C0BRMcm:-NgYyObl-l6f3C0BRMcn:bit8d5b) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt#L42)):*
> ```Kotlin
>             bookingLabel = null,
>             bookingDescriptionI18n = null,
>             createdAt = null
> ```

Could leave these nulls out, since they are default values in VehicleScheduleFrame -> not needed here.


<!-- Sent from Reviewable.io -->

2023-10-13 09:31 UTC, jarkkoka requested changes
> Reviewed 2 of 4 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @culka, @Leitsi, and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 90 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcMemMA8WMUFlGKnt_:-NgcMemMA8WMUFlGKnta:bmf7dz9) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L90)):*
> ```Kotlin
>     @GetMapping("toReplace")
>     fun toReplace(
>         @Valid @RequestParam
> ```

This `@Valid` annotation is ineffective. The actual validation for `targetPriority` is done in the method body.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 92 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcMptg9voVNbUHHdy1:-NgcMptg9voVNbUHHdy2:b7rtqix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L92)):*
> ```Kotlin
>         @Valid @RequestParam
>         targetPriority: Int,
>         @Valid @RequestParam
> ```

This `@Valid` annotation is also ineffective. An exception is thrown earlier (by Spring Boot) if UUID could not be deserialized from input value.


<!-- Sent from Reviewable.io -->

2023-10-13 09:34 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @culka, @Leitsi, and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 102 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcNX-xAU74git0bKsU:-NgcNX-xAU74git0bKsV:bi95gse) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L102)):*
> ```Kotlin
>         val vehicleScheduleFrameIds = replaceTimetablesService.fetchVehicleScheduleFramesToReplace(
>             stagingVehicleScheduleFrameId,
>             TimetablesPriority.fromInt(targetPriority)
> ```

`TimetablesPriority.fromInt(targetPriority)` is done twice. Refactor to do it only once.


<!-- Sent from Reviewable.io -->

2023-10-13 09:49 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 1 of 5 files reviewed, 10 unresolved discussions (waiting on @culka, @Leitsi, and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 88 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcQR6B-MooRofNs3yg:-NgcQR6B-MooRofNs3yh:bt1m9cg) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L88)):*
> ```Kotlin
>     )
> 
>     @GetMapping("toReplace")
> ```

IMO including capital letters in the path is not a good idea nor a common convention. Use hyphens to improve readability.

See, for example this, for designing URI paths:

<https://blog.restcase.com/7-rules-for-rest-api-uri-design/>
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 89 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcQAmwBAjjr7P-k25A:-NgcQAmwBAjjr7P-k25B:b7igmkr) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L89)):*
> ```Kotlin
> 
>     @GetMapping("toReplace")
>     fun toReplace(
> ```

`toReplace` name is really not descritive. For example, `getFrameIdsToBeReplaced`


<!-- Sent from Reviewable.io -->

2023-10-13 09:52 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 1 of 5 files reviewed, 10 unresolved discussions (waiting on @culka, @Leitsi, and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 89 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcQAmwBAjjr7P-k25A:-NgcRiXB2D7Vm_YXNRmN:bqebg19) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L89)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`toReplace` name is really not descritive. For example, `getFrameIdsToBeReplaced`
</blockquote></details>

...and the method name does not need to be the same as URI path.


<!-- Sent from Reviewable.io -->

2023-10-13 09:54 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 1 of 5 files reviewed, 11 unresolved discussions (waiting on @culka, @Leitsi, and @Perholehto)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt` line 131 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcSEva9qk5XP09Lsh4:-NgcSEva9qk5XP09Lsh5:bjj54wq) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt#L131)):*
> ```Kotlin
>         }
>     }
>     companion object {
> ```

Separate `companion object` from the rest by an empty line to improve readability.


<!-- Sent from Reviewable.io -->

2023-10-16 05:58 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 1 of 5 files reviewed, 11 unresolved discussions (waiting on @culka, @jarkkoka, and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 88 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcQR6B-MooRofNs3yg:-Ngr2uWmDrHVrlq1qTz2:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L88)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO including capital letters in the path is not a good idea nor a common convention. Use hyphens to improve readability.

See, for example this, for designing URI paths:

<https://blog.restcase.com/7-rules-for-rest-api-uri-design/>
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 89 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcQAmwBAjjr7P-k25A:-Ngr2uze3oonAT1HPtHM:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L89)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

...and the method name does not need to be the same as URI path.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 90 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcMemMA8WMUFlGKnt_:-Ngr2vTy-VOS8O4WLVTH:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L90)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This `@Valid` annotation is ineffective. The actual validation for `targetPriority` is done in the method body.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 92 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcMptg9voVNbUHHdy1:-Ngr2vsJ-yrNkX2hYndA:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L92)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This `@Valid` annotation is also ineffective. An exception is thrown earlier (by Spring Boot) if UUID could not be deserialized from input value.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 102 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcNX-xAU74git0bKsU:-Ngr2wFy4pFAddgfTEkd:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L102)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`TimetablesPriority.fromInt(targetPriority)` is done twice. Refactor to do it only once.
</blockquote></details>

Done.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt` line 42 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgYyObl-l6f3C0BRMcm:-Ngr2zSN1AIjAQinm6AH:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt#L42)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could leave these nulls out, since they are default values in VehicleScheduleFrame -> not needed here.
</blockquote></details>

Done.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt` line 131 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgcSEva9qk5XP09Lsh4:-Ngr3-23E0SoZ1bqm-27:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt#L131)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Separate `companion object` from the rest by an empty line to improve readability.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt` line 17 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgYxq35BWFagoENNpQz:-Ngr31fKEp_AiC-bvVM2:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/54bcb111525d6ff4ad2775c521c307e15b4d7abd/src/main/kotlin/fi/hsl/jore4/timetables/service/ReplaceTimetablesService.kt#L17)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This probably shouldn't be here, not used from this service.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-16 06:40 UTC, culka reviewed
> Reviewed 1 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: all files reviewed, 9 unresolved discussions (waiting on @jarkkoka and @Leitsi)



<!-- Sent from Reviewable.io -->

2023-10-16 09:23 UTC, jarkkoka requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: all files reviewed, 7 unresolved discussions (waiting on @Leitsi and @Perholehto)

___
*[`README.md` line 95 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgrjYt81-U8LCvbU64x:-NgrjYt81-U8LCvbU64y:b-cxqdw2) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/README.md#L95)):*
> ```Markdown
>   }
>   ```
> - `GET /timetables/toReplace`: Fetch the vehicle schedule frame IDs slated for replacement,
> ```

This should be updated as well: `to-replace`
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 99 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgriJJ53oaN3e_kMTb-:-NgriJJ53oaN3e_kMTb0:btqlit0) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L99)):*
> ```Kotlin
> 
>         val targetPriorityEnumResult = runCatching { TimetablesPriority.fromInt(targetPriority) }
>         if (targetPriorityEnumResult.isFailure) {
> ```

This is ok now.

Personally, I prefer more fluent functional style (using single expression) like this:

```kotlin
return runCatching { TimetablesPriority.fromInt(targetPriority) }  
    .getOrNull()  
    ?.let { validPriority: TimetablesPriority ->  
  
        val vehicleScheduleFrameIds = replaceTimetablesService  
            .fetchVehicleScheduleFramesToReplace(stagingVehicleScheduleFrameId, validPriority)  
            .mapNotNull { it.vehicleScheduleFrameId }  
  
        ResponseEntity  
            .status(HttpStatus.OK)  
            .body(ToReplaceTimetablesResponseBody(toReplaceVehicleScheduleFrameIds = vehicleScheduleFrameIds))  
    }  
    ?: throw TargetPriorityParsingException("Failed to parse target priority", targetPriority)
```

From the above code, you can more easily observe the immutable nature of processing.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt` line 80 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-Ngrm3W29oiB43CMSS2O:-NgrkY-37_hBsPJLqVqB:bpbk3sm) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt#L80)):*
> ```Kotlin
>                     """
>                     {
>                       "toReplaceVehicleScheduleFrameIds": ${TimetablesToReplaceApiTest.OBJECT_MAPPER.writeValueAsString(defaultToReplaceIds)}
> ```

This class name prefix is not needed and can be removed.

But actually you can replace this whole expression with a simple variable (and remove the `OBJECT_MAPPER`):

```kotlin
$defaultToReplaceIds
```
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt` line 124 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgrmKib9YizhR4xHJ0F:-NgrmKib9YizhR4xHJ0G:b-dw0s83) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt#L124)):*
> ```Kotlin
>     }
>     companion object {
>         private val OBJECT_MAPPER = ObjectMapper()
> ```

Read the comment above. You don't need an `OBJECT_MAPPER` instance. Therefore, you can also remove the `companion object` (unless you decide to move `defaultVehicleScheduleFrames` and `defaultToReplaceIds` inside it, which I consider a better style).


<!-- Sent from Reviewable.io -->

2023-10-16 12:05 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @culka, @jarkkoka, and @Leitsi)

___
*[`README.md` line 95 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgrjYt81-U8LCvbU64x:-Ngs5XlD6_JV9HBlPImo:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/README.md#L95)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This should be updated as well: `to-replace`
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 99 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgriJJ53oaN3e_kMTb-:-NgsMY9C1uakbWuEKaKp:bg6y04z) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L99)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This is ok now.

Personally, I prefer more fluent functional style (using single expression) like this:

```kotlin
return runCatching { TimetablesPriority.fromInt(targetPriority) }  
    .getOrNull()  
    ?.let { validPriority: TimetablesPriority ->  
  
        val vehicleScheduleFrameIds = replaceTimetablesService  
            .fetchVehicleScheduleFramesToReplace(stagingVehicleScheduleFrameId, validPriority)  
            .mapNotNull { it.vehicleScheduleFrameId }  
  
        ResponseEntity  
            .status(HttpStatus.OK)  
            .body(ToReplaceTimetablesResponseBody(toReplaceVehicleScheduleFrameIds = vehicleScheduleFrameIds))  
    }  
    ?: throw TargetPriorityParsingException("Failed to parse target priority", targetPriority)
```

From the above code, you can more easily observe the immutable nature of processing.
</blockquote></details>

Did not change this.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt` line 80 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-Ngrm3W29oiB43CMSS2O:-Ngs6CqZEoxXHO5YeuPl:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt#L80)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This class name prefix is not needed and can be removed.

But actually you can replace this whole expression with a simple variable (and remove the `OBJECT_MAPPER`):

```kotlin
$defaultToReplaceIds
```
</blockquote></details>

Done.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt` line 124 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgrmKib9YizhR4xHJ0F:-Ngs6C4Q3JHHGDJiXWPz:b-5x94ge) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToReplaceApiTest.kt#L124)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Read the comment above. You don't need an `OBJECT_MAPPER` instance. Therefore, you can also remove the `companion object` (unless you decide to move `defaultVehicleScheduleFrames` and `defaultToReplaceIds` inside it, which I consider a better style).
</blockquote></details>

Removed `companion object`


<!-- Sent from Reviewable.io -->

2023-10-16 12:12 UTC, culka approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @jarkkoka and @Leitsi)



<!-- Sent from Reviewable.io -->

2023-10-16 12:19 UTC, jarkkoka approved these changes
The commit message points to an outdated path, but fixing this isn't that critical.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-:-NgsP3yB8DLuPzisvuU7:bus2gef)* status: all files reviewed, 4 unresolved discussions (waiting on @Leitsi and @Perholehto)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 190 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgJVK5P8tg0LYrAk4_U:-NgsPiB80aiPgm4tuELZ:bz7t0za) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6f5857f7d02a41c41efd996d1ff9b498dbad6056/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L190)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I think it's possible that add a custom validation annotation. I tried to add that annotation but didn't succeed. Don't wanna use more time for this now... I think Teemu or Jarkko can solve it in minutes..
</blockquote></details>

Let's solve this in a separate PR. Can't directly suggest a change.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 99 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9#-NgriJJ53oaN3e_kMTb-:-NgsPIpX2qFKWACAmFPd:btb2b9l) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/d18c5bba02878733695ea08266439bc47edfee69/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L99)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Did not change this.
</blockquote></details>

That's ok. Not a problem. The previous comment was just a hint that many of the team's developers prefer the functional programming style.


<!-- Sent from Reviewable.io -->

2023-10-16 12:22 UTC, jarkkoka approved these changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/9)* status: all files reviewed, 3 unresolved discussions (waiting on @Leitsi)



<!-- Sent from Reviewable.io -->

2023-10-17 07:33 UTC, merged